language: node_js
node_js:
     - 7.0
     - 8.0
     - stable
cache:
  directories:
    - node_modules
before_install:
    - yarn install
script:
  - yarn lint
  - yarn ftest
after_script:
  - yarn coverage